// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADZG8tWutFlMUE2xPxERqJyt3d028laNw',
    appId: '1:1057656790392:android:018b70cf6f7d08022efc8d',
    messagingSenderId: '1057656790392',
    projectId: 'vedic-maths-d7d74',
    storageBucket: 'vedic-maths-d7d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNi-qatJlP60QNSgj0kP5sb7OZKJXMM2A',
    appId: '1:1057656790392:ios:9139ce7a1b2e28502efc8d',
    messagingSenderId: '1057656790392',
    projectId: 'vedic-maths-d7d74',
    storageBucket: 'vedic-maths-d7d74.firebasestorage.app',
    iosBundleId: 'com.example.vedicMaths',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq7DNvC60QEsdIs0j1s2SIaTITloIcjjk',
    appId: '1:1057656790392:web:f5e4b527f112125a2efc8d',
    messagingSenderId: '1057656790392',
    projectId: 'vedic-maths-d7d74',
    authDomain: 'vedic-maths-d7d74.firebaseapp.com',
    storageBucket: 'vedic-maths-d7d74.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNi-qatJlP60QNSgj0kP5sb7OZKJXMM2A',
    appId: '1:1057656790392:ios:9139ce7a1b2e28502efc8d',
    messagingSenderId: '1057656790392',
    projectId: 'vedic-maths-d7d74',
    storageBucket: 'vedic-maths-d7d74.firebasestorage.app',
    iosBundleId: 'com.example.vedicMaths',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq7DNvC60QEsdIs0j1s2SIaTITloIcjjk',
    appId: '1:1057656790392:web:252e740935ac1bf92efc8d',
    messagingSenderId: '1057656790392',
    projectId: 'vedic-maths-d7d74',
    authDomain: 'vedic-maths-d7d74.firebaseapp.com',
    storageBucket: 'vedic-maths-d7d74.firebasestorage.app',
  );

}